'use client';

import { PipelineResult } from '@/types/types';
import dynamic from 'next/dynamic';

// Dynamic import the primitive renderer to avoid SSR issues
const PrimitiveRenderer = dynamic(() => import('./PrimitiveRenderer'), {
    ssr: false,
});

const SceneRenderer = dynamic(() => import('./SceneRenderer'), {
    ssr: false,
});

interface Viewer3DProps {
    result: PipelineResult;
    wireframe: boolean;
    autoRotate: boolean;
    simplified: boolean;
    explodedView?: boolean;
    isolated: string | null;
    onIsolate: (name: string | null) => void;
}

export default function Viewer3D({
    result,
    wireframe,
    autoRotate,
    simplified,
    explodedView = false,
    isolated,
    onIsolate,
}: Viewer3DProps) {
    // ─── Case 1: Sketchfab embed ───────────────────────────
    if (result.source === 'sketchfab' && result.model_uid) {
        const embedUrl = `https://sketchfab.com/models/${result.model_uid}/embed?autospin=0.2&autostart=1&ui_theme=dark&ui_infos=0&ui_watermark=0&ui_stop=0`;

        return (
            <iframe
                className="sketchfab-embed"
                title={`3D model of ${result.concept.concept}`}
                src={embedUrl}
                allow="autoplay; fullscreen; xr-spatial-tracking"
                allowFullScreen
            />
        );
    }

    // ─── Case 2: Tripo model (external URL) ────────────────
    if (result.source === 'tripo' && result.model_url) {
        // For Tripo models, we show the model URL info and a loading message
        // In a full implementation, we'd download the GLB and render it
        return (
            <div
                style={{
                    width: '100%',
                    height: '100%',
                    display: 'flex',
                    flexDirection: 'column',
                    alignItems: 'center',
                    justifyContent: 'center',
                    gap: '16px',
                    color: 'var(--text-secondary)',
                }}
            >
                <div style={{ fontSize: '64px' }}>🤖</div>
                <h2
                    style={{
                        fontFamily: 'Outfit, sans-serif',
                        fontWeight: 600,
                        fontSize: '20px',
                        color: 'var(--text-primary)',
                    }}
                >
                    AI-Generated Model Ready
                </h2>
                <p style={{ fontSize: '14px', maxWidth: '400px', textAlign: 'center', lineHeight: 1.6 }}>
                    A 3D model of <strong>{result.concept.concept}</strong> has been
                    generated by Tripo AI.
                </p>
                <a
                    href={result.model_url}
                    target="_blank"
                    rel="noopener noreferrer"
                    style={{
                        padding: '10px 24px',
                        background: 'var(--accent-gradient)',
                        color: 'white',
                        borderRadius: 'var(--radius-xl)',
                        textDecoration: 'none',
                        fontSize: '14px',
                        fontWeight: 600,
                    }}
                >
                    View / Download Model ↗
                </a>
            </div>
        );
    }

    // ─── Case 3: Primitive composition ─────────────────────
    if (result.source === 'primitive' && result.primitiveConfig) {
        return (
            <PrimitiveRenderer
                config={result.primitiveConfig}
                wireframe={wireframe}
                simplified={simplified}
                autoRotate={autoRotate}
                isolated={isolated}
                onIsolate={onIsolate}
            />
        );
    }

    // ─── Case 4: Text-generated Scene ──────────────────────
    if (result.source === 'scene' && result.sceneConfig) {
        return (
            <SceneRenderer
                config={result.sceneConfig}
                wireframe={wireframe}
                autoRotate={autoRotate}
                explodedView={explodedView}
                isolated={isolated}
                onIsolate={onIsolate}
            />
        );
    }

    // ─── Fallback: nothing to show ─────────────────────────
    return (
        <div className="viewer-placeholder">
            <div className="viewer-placeholder-icon">❌</div>
            <h2>No Model Available</h2>
            <p>Could not load a 3D visualization for this concept.</p>
        </div>
    );
}
